//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "main_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub f_user_id: Option<i32>,
    pub merchant_id: i32,
    pub membership_id: i32,
    pub coach_id: i32,
    pub coach_plus_id: i32,
    pub account: String,
    pub nickname: String,
    pub phone: String,
    pub open_id: String,
    pub avatar: String,
    pub password: String,
    pub point: i32,
    #[sea_orm(column_type = "Float", nullable)]
    pub gt_tdee: Option<f32>,
    pub invite_code: Option<String>,
    pub sign_num: Option<i32>,
    pub gender: i8,
    pub status: i8,
    pub is_delete: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
